name: tracer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.10=hd590300_0
  - bowtie=1.3.1=py38h70e88c0_6
  - bowtie2=2.5.2=py38he00c5e5_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.21.0=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - collectl=4.0.4=1
  - expat=2.5.0=hcb278e6_1
  - fastool=0.1.4=he4a0461_8
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - graphite2=1.3.13=h58526e2_1001
  - harfbuzz=8.2.1=h3d44ed6_0
  - hdf5=1.12.1=nompi_h4df4325_104
  - htslib=1.18=h81da01d_0
  - icu=73.2=h59595ed_0
  - igblast=1.21.0=pl5321h6a68c12_1
  - java-jdk=8.0.92=1
  - jellyfish=1.0.1=py38h0cc4f7c_1
  - kallisto=0.48.0=h15996b6_2
  - keyutils=1.6.1=h166bdaf_0
  - kmer-jellyfish=2.3.0=h9f5acd7_3
  - krb5=1.21.2=h659d440_0
  - lcms2=2.15=hb7c19ff_3
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgirepository=1.78.1=h003a4f0_1
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - libnghttp2=1.55.1=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.44.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - ncbi-vdb=3.0.0=pl5321h87f3376_0
  - ncurses=6.4=h59595ed_2
  - openjdk=21.0.1=haa376d0_0
  - openssl=3.1.4=hd590300_0
  - parafly=r2013_01_21=0
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=4_hd590300_perl5
  - perl-threaded=5.32.1=hdfd78af_1
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.25.1=py38h1a1917b_0
  - pygobject=3.42.2=py38h6284730_1
  - python=3.8.18=hd12c33a_0_cpython
  - python_abi=3.8=4_cp38
  - readline=8.2=h8228510_1
  - samtools=1.18=h50ea8bc_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - slclust=02022010=1
  - tbb=2021.10.0=h00ab1b0_2
  - tk=8.6.13=h2797004_0
  - trimmomatic=0.39=hdfd78af_2
  - trinity=2.1.1=6
  - wheel=0.41.3=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - biopython==1.77
      - cffi==1.16.0
      - contourpy==1.1.1
      - cryptography==38.0.3
      - cycler==0.11.0
      - decorator==5.1.1
      - fonttools==4.43.1
      - future==0.18.2
      - idna==3.4
      - importlib-metadata==6.8.0
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - keyring==23.11.0
      - keyrings-alt==4.2.0
      - kiwisolver==1.4.5
      - levenshtein==0.20.8
      - matplotlib==3.6.2
      - mock==4.0.3
      - more-itertools==10.1.0
      - networkx==1.11
      - numpy==1.23.4
      - packaging==23.2
      - pandas==1.5.1
      - pbr==5.11.0
      - pillow==10.1.0
      - prettytable==3.5.0
      - pyasn1==0.5.0
      - pycparser==2.21
      - pycrypto==2.6.1
      - pydotplus==2.0.2
      - pyparsing==2.4.6
      - python-dateutil==2.8.2
      - python-levenshtein==0.20.8
      - pytz==2022.6
      - pyxdg==0.28
      - rapidfuzz==2.15.2
      - scipy==1.9.3
      - seaborn==0.12.0
      - secretstorage==3.3.3
      - six==1.14.0
      - tracer==0.6
      - wcwidth==0.2.9
      - zipp==3.17.0
prefix: /cellar/users/pdow/miniconda3/envs/tracer
